# Generated by Django 2.1.1 on 2018-09-17 09:30

import datetime
from django.db import migrations
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flims',
            options={'verbose_name_plural': 'Flims'},
        ),
        migrations.AddField(
            model_name='flims',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=datetime.datetime(2018, 9, 17, 9, 30, 48, 971297, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
