# Generated by Django 2.1.1 on 2018-09-17 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0002_auto_20180917_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='flims',
            name='actor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flims',
            name='description',
            field=models.TextField(default=datetime.datetime(2018, 9, 17, 13, 7, 31, 741862, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flims',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
