# Generated by Django 2.1.1 on 2018-09-17 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0003_auto_20180917_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='flims',
            name='director',
            field=models.CharField(default=datetime.datetime(2018, 9, 17, 13, 48, 12, 539739, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
