# Generated by Django 2.1.1 on 2018-09-18 13:18

from django.db import migrations, models
import django.db.models.deletion
import flims.models


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0005_flims_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlimsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=flims.models.image_upload_to)),
                ('flim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flims.Flims')),
            ],
        ),
    ]
