# Generated by Django 2.1.1 on 2018-09-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0007_auto_20180920_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flims',
            name='thumbnail',
        ),
    ]
