# Generated by Django 2.1.1 on 2018-10-10 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flims', '0008_remove_flims_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='flims',
            name='actress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flims',
            name='assistant_camera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flims',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flims',
            name='production',
            field=models.CharField(default=datetime.datetime(2018, 10, 10, 9, 31, 48, 959210, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
